spring.application.name=gestionCimetieres
#DataSource settings for MySQL database:
spring.datasource.url=jdbc:mysql://localhost:3306/cimetieres?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password =
#Show or not log for each sql query
spring.jpa.show-sql= true
# Hibernate ddl auto (create, update, none)
spring.jpa.hibernate.ddl-auto = update
#Change server port. Default value is 8080
server.port=9999
#DataSource settings for Oracle database:
#spring.datasource.driver-class-#name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:Xe
#spring.datasource.username= username
#spring.datasource.password= password
jwt.secret=cimetieressfax2024secretkeyverylongatleast32chars
jwt.expiration=86400000
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp